# Generated by Django 4.1.6 on 2023-02-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nations')),
            ],
        ),
        migrations.CreateModel(
            name='TankType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tank_types')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('tank_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tier', models.IntegerField()),
                ('is_premium', models.BooleanField()),
                ('is_gift', models.BooleanField()),
                ('is_premium_igr', models.BooleanField()),
                ('is_wheeled', models.BooleanField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tankopedia.nation')),
                ('tank_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tankopedia.tanktype')),
            ],
        ),
        migrations.CreateModel(
            name='TankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tankopedia.tank')),
            ],
            options={
                'unique_together': {('tank', 'name')},
            },
        ),
    ]
