# Generated by Django 4.1.6 on 2023-02-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tankopedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tank',
            old_name='tank_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='tankimage',
            old_name='image',
            new_name='url',
        ),
    ]
